{"name": "test_login_0_failed_by_wrong_datas[data3]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '18684705531', 'passwd': 'py', 'check': '请输入6-24位密码'}"}], "start": 1562346501926, "stop": 1562346502154, "uuid": "26d60c7f-29b4-4170-b51b-1354298e4cb6", "historyId": "d00564395d75e843a820c65d1befe5e0", "fullName": "TestCases.test_login.TestLogin#test_login_0_failed_by_wrong_datas[data3]", "labels": [{"name": "story", "value": "登录失败"}, {"name": "feature", "value": "登录页面功能"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "9160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}