{"name": "test_logins_0_failed_by_wrong_datas[data2]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '186847', 'passwd': 'python', 'check': '用户不存在'}"}], "start": 1562259118706, "stop": 1562259119759, "uuid": "f390a87b-7b0e-4227-8d6c-6f5abeed6421", "historyId": "6128ffe3d9b95ee7f71ca108519ca8a4", "fullName": "TestCases.test_loginpai.TestLogin#test_logins_0_failed_by_wrong_datas[data2]", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginpai"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "16424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginpai"}]}